name: stock_price_aggregator
version: "0.0.1"
config-version: 2

profile: stock_price_aggregator

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: target

clean-targets:
	- target
	- dbt_packages
	- logs

models:
  stock_price_aggregator:
  
    staging:
      +materialized: table
      +schema: "{{ env_var('STAGING_DATABASE')}}"
    
    
    intermediate:
      +materialized: table
      +schema: "{{ env_var('INTERMEDIATE_DATABASE')}}"
      
    
    marts:
      +materialized: table
      +schema: "{{ env_var('MARTS_DATABASE')}}"
