stock_price_aggregator:
  target: prod

  outputs:
    prod:
      type: athena
      threads: 8
      database: AwsDataCatalog
      schema: default

      workgroup: "{{ env_var('DBT_ATHENA_WORKGROUP')}}"

      s3_staging_dir: "{{ env_var('S3_STAGING_DIR')}}"
      s3_data_dir: "{{ env_var('S3_DATA_DIR')}}"
      s3_data_naming: schema_table

      region_name: "{{ env_var('AWS_REGION')}}"

